 default:
  source: "path/of/excelfile.xlsx"
  lsucv_cattle: 0.5
  lsucv_sheep: 0.1
  lsucv_pig: 0.2
  BiodiversityIndicator: "Agrobiodiversity"
  
 global_north:
  source: "path/of/excelfile.xlsx"
  lsucv_cattle: 0.9
  lsucv_sheep: 0.15
  lsucv_pig: 0.25
  BiodiversityIndicator: "Biodiversity"
  
 global_south:
  source: "path/of/excelfile.xlsx"
  lsucv_cattle: 0.5
  lsucv_sheep: 0.1
  lsucv_pig: 0.2
  BiodiversityIndicator: "Biodiversity"
  
 
